"""Final title tags (≤ 70 characters; home ≤ 80) and meta descriptions (≤ 160) by slug.

Kept in one place so they can be tuned without touching page copy. Applied by base.page().
"""
META = {
    "home": ("Frost Law Group | Summerville SC Estate, Probate & Criminal Defense Attorneys",
        "Jack and Tara Frost handle estate planning, probate, criminal defense and landlord-tenant matters for Dorchester, Berkeley and Charleston County families."),
    "about-us": ("Our Team | Frost Law Group, Summerville SC",
                 "Meet Jack and Tara Frost, a former detective and a former probate judge, plus paralegal Cassie Snyder and two comfort dogs, at Frost Law Group in Summerville."),
    "attorneys/jack-frost": ("Jack C. Frost | Criminal Defense Attorney, Summerville SC",
                             "Jack Frost spent 14 years as a Summerville police officer and Charleston County Sheriff's Office detective before law school. He now defends criminal charges."),
    "team/cassie-snyder": ("Cassie Snyder | Legal Assistant & Paralegal, Summerville SC",
                 "Meet Cassie Snyder, legal assistant and paralegal at Frost Law Group in Summerville, SC. She keeps clients informed and supported at every stage of their case."),
    "attorneys/tara-frost": ("Tara L. Frost | Probate & Estate Planning Attorney, Summerville SC",
                             "Tara Frost served as a Dorchester County Magistrate Judge and Associate Probate Judge before returning to practice. She leads probate and estate planning."),
    "contact-us": ("Contact Frost Law Group | 128 Linwood Lane, Summerville SC",
                   "Call (843) 419-6653 or visit 128 Linwood Lane, Summerville, SC 29483. Hours, a map, directions on local roads from every community we serve, and a contact form."),
    "reviews": ("Client Reviews | Frost Law Group, Summerville SC",
                "What clients say about Frost Law Group's estate planning, probate, criminal defense and injury work in Summerville, and how to leave a review on Google or Yelp."),
    "service-areas": ("Areas We Serve | Dorchester, Berkeley & Charleston County SC",
                      "Frost Law Group serves Summerville, Goose Creek, Ladson, North Charleston, Moncks Corner, Charleston and the rest of the tri-county area. Find your community."),
    "blog": ("In the Know | Local News Explained by Summerville Attorneys",
             "What Lowcountry news means for your estate plan, a probate case or a criminal charge, written by Jack and Tara Frost with links to the original reporting."),
    "faq": ("Frequently Asked Questions | Frost Law Group, Summerville SC",
            "Plain-English answers to the questions Summerville families ask about wills, trusts, probate, guardianship, criminal charges and working with Frost Law Group."),
    "privacy-policy": ("Privacy Policy | Frost Law Group, Summerville SC",
                       "How Frost Law Group's website handles the information you share through its contact form, analytics and embedded maps, and what we do not do with it."),
    # estate planning
    "estate-planning-attorney": ("Estate Planning Attorney in Summerville, SC | Frost Law Group",
                                 "Summerville estate planning attorneys Jack and Tara Frost prepare wills, revocable living trusts, powers of attorney and living wills. Flat fees, plain English."),
    "last-will-and-testament": ("Last Will and Testament Attorney in Summerville, SC",
                                "What a valid South Carolina will requires, what it can cover, and what happens without one. Wills for Summerville families from Frost Law Group."),
    "revocable-trust": ("Revocable Living Trust Attorney in Summerville, SC",
                        "A revocable living trust lets your family skip probate, plans for incapacity and stays private. When a trust beats a will under South Carolina law."),
    "power-of-attorney": ("Power of Attorney in South Carolina | Durable & Health Care",
        "How a South Carolina power of attorney is signed, the recording rule before an agent can act, what an agent may do, and the health care power of attorney."),
    "living-will": ("Living Will in South Carolina | Form, Witnesses & Notary",
        "South Carolina living wills: the Declaration of a Desire for a Natural Death, who may witness it, when physicians follow it, and the health care POA."),
    "asset-protection-trusts": ("Asset Protection Trusts in Summerville, SC | Frost Law Group",
                                "What asset protection really means in South Carolina: irrevocable trusts, Medicaid's five-year look-back, exempt assets and honest limits. Summerville lawyers."),
    "estate-planning-for-blended-families": ("Estate Planning for Blended Families in Summerville, SC",
                                             "Second marriages and stepchildren: how South Carolina's default rules leave someone out, and how a trust-based plan provides for a spouse and your own children."),
    "estate-plan-review": ("Estate Plan Review, Trust Amendments & Restatements | Summerville SC",
                           "Get an existing will or trust reviewed in Summerville, including online and out-of-state documents. Frost Law Group amends or restates trusts and updates plans."),
    "estate-planning-for-business-owners": ("Estate Planning for Business Owners in Summerville, SC",
                                            "Succession plans, buy-sell and operating agreements, powers of attorney that cover the business, and trusts that keep a Lowcountry company running after death."),
    "special-needs-planning": ("Special Needs Trusts & Planning in Summerville, SC | Frost Law Group",
                               "Third-party special needs trusts, ABLE accounts and guardianship options that provide for a loved one with a disability without costing them SSI or Medicaid."),
    "dying-without-a-will-in-south-carolina": ("Dying Without a Will in South Carolina | What Happens Next",
                                               "South Carolina's intestacy rules: what a spouse and children receive, who is left out, who the court appoints, and what a Summerville family should do next."),
    "estate-planning-costs": ("What Estate Planning Costs in Summerville, SC | Flat Fees",
                              "What a will, a trust-based plan and powers of attorney typically cost in the Charleston area, what drives the price, and how Frost Law Group's flat fees work."),
    "high-net-worth-estate-planning": ("Estate Planning for Larger Estates in Summerville, SC",
                                       "Planning for complex portfolios, several properties, businesses and estate-tax exposure: irrevocable trusts, gifting, trustee choice and advisor coordination."),
    # probate
    "probate": ("Probate Attorney in Summerville, SC | Former Probate Judge",
                "Summerville probate attorney Tara Frost, a former Dorchester County probate judge, guides families through estate administration, disputes and guardianship."),
    "probate-process": ("The South Carolina Probate Process, Step by Step",
                        "From the week of death to the day the estate closes: delivering the will, appointment, creditor notice, inventory, taxes, distribution and closing, in SC."),
    "executor-duties": ("Executor Duties in South Carolina | Summerville Probate Attorney",
                        "What a South Carolina personal representative must do, in what order and by when, and the mistakes that create personal liability. From a former probate judge."),
    "executor-disputes": ("Executor Disputes in Summerville, SC Probate Court",
                          "Removal petitions, demands for an accounting, self-dealing claims and contested distributions in the Dorchester, Berkeley and Charleston County probate courts."),
    "small-estate-affidavit": ("SC Small Estate Affidavit | $45,000 Limit, Form 420ES & Fees",
        "When a South Carolina estate can skip probate: the $45,000 small estate affidavit (Form 420ES), what counts toward the limit, the fee and how to file."),
    "will-contests": ("Will Contests & Probate Litigation in Summerville, SC",
                      "Grounds to contest a will in South Carolina—capacity, undue influence, fraud and execution—who can bring one, the deadlines, and how the probate court decides."),
    "guardianship-and-conservatorship": ("Guardianship & Conservatorship Attorney in Summerville, SC",
                                         "Guardianship and conservatorship for incapacitated adults and minors in Dorchester, Berkeley and Charleston County probate courts, including contested cases."),
    "trust-administration": ("Trust Administration & Inherited Assets in Summerville, SC",
                             "Help for trustees and beneficiaries after a death: trustee duties under the South Carolina Trust Code, notices and accountings, and managing inherited assets."),
    "probate-courts": ("Dorchester, Berkeley & Charleston Probate Courts | Guide",
        "Which probate court has your case: Dorchester (St. George), Berkeley (Moncks Corner) or Charleston (Broad Street), with addresses, hours and a guide to each."),
    # criminal defense
    "criminal-defense": ("Criminal Defense Attorney in Summerville, SC | Former Detective",
                         "Summerville criminal defense attorney Jack Frost spent 14 years in law enforcement. Drug charges, domestic violence, bond hearings, warrants and expungements."),
    "dui-lawyer-summerville-sc": ("First-Offense DUI in South Carolina | Penalties & Defense",
        "First-offense DUI in South Carolina: fines by breath result, 48 hours to 90 days in jail, the six-month suspension, ADSAP and the ignition interlock rule."),
    "drug-charges": ("Drug Charge Lawyer in Summerville, SC | Former Narcotics Detective",
                     "Simple possession, PWID and trafficking charges in the tri-county area, defended by former narcotics detective Jack Frost. Conditional discharge and PTI."),
    "domestic-violence-defense": ("Domestic Violence 3rd Degree in SC | Penalties & Defense",
        "Domestic violence degrees under S.C. Code § 16-25-20: penalties, bond conditions, the firearm ban, expungement and how CDV cases are defended."),
    "bond-hearings": ("Bond Hearings in Dorchester & Berkeley County | Summerville Attorney",
                      "What happens at a South Carolina bond hearing, how amounts and conditions are set, how to get a bond reduced, and why a lawyer at the first hearing matters."),
    "expungements": ("Expungement in South Carolina | Eligibility, Cost & Time",
        "Who qualifies for expungement in South Carolina, the three- and five-year waits, the $250 solicitor fee plus court and SLED fees, and how long it takes."),
    "traffic-tickets": ("Driving Under Suspension & Traffic Tickets in SC | Lawyer",
        "Driving under suspension penalties under § 56-1-460, how South Carolina points add up to a suspension, and why paying a ticket is a guilty plea."),
    "arrest-warrants": ("Bench Warrants in South Carolina | How to Check & Clear One",
        "How to check for a bench warrant or arrest warrant in Dorchester, Berkeley or Charleston County, and how to clear it with the least damage to you."),
    # county guides, minors, Charleston pages
    "dorchester-county-probate-court": ("Dorchester County Probate Court Guide | St. George, SC",
        "Address, phone and hours for the Dorchester County Probate Court, the worksheet and seminar required to file without a lawyer, forms, fees and timelines."),
    "berkeley-county-probate-court": ("Berkeley County Probate Court Guide | Moncks Corner, SC",
        "Address, hours, walk-in and drop-box rules at the Berkeley County Probate Court, plus forms, fees and timelines for Goose Creek and Nexton families."),
    "charleston-county-probate-court": ("Charleston County Probate Court Guide | 84 Broad Street",
        "The Charleston County Probate Court's two Broad Street offices, EZ-Filing, estate appointments and free workshops, plus forms, fees and timelines."),
    "guardianship-of-minors": ("Guardianship of a Minor in South Carolina | Courts & Money",
        "Family Court names a guardian of a child's person; probate court names a conservator for the money. The $2,500 and $25,000 settlement thresholds, explained."),
    "probate-attorney-charleston-sc": ("Probate Attorney Serving Charleston, SC | Former Judge",
        "Probate and estate administration in the Charleston County Probate Court from a former probate judge thirty minutes up I-26: estates, real estate, disputes."),
    "estate-planning-attorney-charleston-sc": ("Estate Planning Attorney Serving Charleston, SC | Frost Law",
        "Wills, trusts, powers of attorney and living wills for Charleston County families: coastal property, recording at the Charleston ROD, new-resident reviews."),
    # landlord-tenant
    "eviction-lawyer-summerville-sc": ("Eviction & Landlord-Tenant Attorney in Summerville, SC",
        "Evictions, tenant defense, security deposits and leases in the Dorchester, Berkeley and Charleston County magistrate courts, from a former magistrate judge."),
    "south-carolina-eviction-process": ("South Carolina Eviction Process | Notices, Rule & Writ",
        "How eviction works in South Carolina: the five- and fourteen-day notices, the $40 Application for Ejectment, the tenant's ten days, the hearing and the writ."),
    "south-carolina-security-deposit-law": ("SC Security Deposit Law | 30-Day Rule & Triple Damages",
        "South Carolina security deposit law (§ 27-40-410): the thirty-day return rule, lawful deductions, the three-times penalty and how to sue in magistrate court."),
    # blog
    "blog/new-summerville-residents-estate-plan": ("Moved to Summerville? Five Documents to Redo | Frost Law Group",
        "New to Dorchester or Berkeley County? Which out-of-state wills and powers of attorney still work in South Carolina, which do not, and which county is yours."),
    "blog/hurricane-season-documents-dorchester-county": ("Hurricane Season: Four Documents for the Go-Bag | Frost Law Group",
        "Before the next evacuation order: the will, powers of attorney, insurance and deed list to secure now, and what SC law does when an original will is lost."),
    "blog/guardianship-aging-parent-summerville": ("Guardianship for an Aging Parent in Summerville | Frost Law Group",
        "Who handles guardianship for a parent in Summerville? A former probate judge explains the process, the cost, and when a power of attorney can still avoid it."),
    "blog/expungement-clinics-who-qualifies-dorchester-berkeley": ("Expungement Clinics: Who Qualifies in Dorchester & Berkeley",
        "Before you stand in line at an expungement clinic, a former officer explains who qualifies under South Carolina's 2018 reforms and what a clinic can do."),
    "blog/school-zone-traffic-enforcement-summerville": ("School-Zone Traffic Enforcement in Summerville | What a Ticket Costs",
        "Each August Summerville police announce school-zone patrols. A former officer explains the points, the insurance hit, the school-bus charge, and when to fight."),
    "blog/do-i-need-a-probate-lawyer-south-carolina-reddit": ("Do I Need a Probate Lawyer in SC? A Former Judge Answers",
        "The r/Charleston question, answered by a former Dorchester County probate judge: when you can handle an estate yourself, when you should not, and how to tell."),
    "blog/domestic-violence-arrest-first-72-hours-dorchester-county": ("After a Domestic Violence Arrest: The First 72 Hours | Frost Law Group",
        "Bond, the no-contact order, going home, and the three mistakes that turn one charge into two after a domestic violence arrest in Dorchester County."),
    "blog/summerville-address-berkeley-county-what-it-means": ("Summerville Address, Berkeley County: What It Means | Frost Law Group",
        "Nexton, Cane Bay and Carnes Crossroads are in Berkeley County. That decides where an estate is probated, where a guardianship is filed and which court you face."),
    # legal pages
    "terms-of-use": ("Terms of Use & Legal Disclaimer | Frost Law Group, Summerville SC",
        "The rules for using frostlawgroupsc.com: no legal advice, no attorney-client relationship until an engagement agreement, attorney advertising notice, SC law."),
    "accessibility": ("Accessibility Statement | Frost Law Group, Summerville SC",
        "How Frost Law Group's website and Summerville office are built to be usable by everyone, known limitations, and how to report a problem or ask for help."),
}
